/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://maven.hq.hydraulic.software") // Hydraulic Conveyor plugin (used by :app)
    }
}

rootProject.name = "Azkar"

include("data")
include("app")
include("domain")