/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "Azkar"

include("data")
include("app")
include("utils")
include("domain")