package com.azkar.data.entity;

import jakarta.persistence.*;
import java.time.Instant;
import lombok.*;
import org.jspecify.annotations.Nullable;

/// Entity representing a “favorite” remembrance (zikr) in the system.
///
/// A favorite marks a [RemembranceEntity] as bookmarked by the user
/// for quicker access to frequently used or personally significant zikr.
///
/// ## Database Mapping
/// - Table: **favorite**
/// - Primary key: `id`
/// - Automatically managed `createdAt` timestamp
/// - One-to-one association with [RemembranceEntity]
///
/// ## Lifecycle
/// - Created when a remembrance is favorited.
/// - `createdAt` is populated by the database using
/// `DEFAULT (unixepoch())` and cannot be changed
/// from application code.
/// - Deleted automatically if the associated remembrance is removed
///
/// @see RemembranceEntity
@Entity
@Table(name = "favorite")
@SuppressWarnings("NullAway.Init")
@NoArgsConstructor(access = AccessLevel.PROTECTED) // Required by JPA @Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString(onlyExplicitlyIncluded = true)
public class FavoriteEntity {

    /// Primary key. Auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    @ToString.Include
    @Getter
    private @Nullable Long id;

    /// Timestamp when the remembrance was favorited.
    ///
    /// Set automatically by the database with `DEFAULT (unixepoch())`.
    /// Not insertable or updatable from application code.
    ///
    /// Intended for:
    /// - Displaying “favorited on” dates
    /// - Sorting favorites by recency
    ///
    @Column(
        name = "created_at",
        nullable = false,
        insertable = false,
        updatable = false
    )
    @Getter
    private @Nullable Instant createdAt;

    /// The remembrance that has been marked as a favorite.
    ///
    /// This is the inverse side of the one-to-one mapping:
    /// [RemembranceEntity] holds the owning side via its [favorite][RemembranceEntity#favorite] field.
    @OneToOne(mappedBy = "favorite")
    @Getter
    @Setter(AccessLevel.PACKAGE)
    private @Nullable RemembranceEntity remembrance;

    /// Builder constructor for [FavoriteEntity].
    ///
    /// @param id          optional database identifier (null when creating new entities)
    /// @param remembrance the associated remembrance
    @Builder
    private FavoriteEntity(@Nullable Long id, RemembranceEntity remembrance) {
        this.id = id;
        this.remembrance = remembrance;
    }
}
