-- ============================================================================
-- Table: favorite
-- Purpose:
--   Stores remembrances (اذكار) marked as favorites by the single user.
--   Allows quick access to frequently used or personally significant zikr.
--
-- Columns:
--   id         : Unique auto-incrementing identifier.
--   created_at : Timestamp when the favorite was added.
--
-- Constraints & Behavior:
--   - PRIMARY KEY(id) with auto-increment.
-- =========================================================================
CREATE TABLE IF NOT EXISTS favorite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Table: remembrance
-- Each row represents one "remembrance" (اذكار): the core zikr record itself.
--
-- Columns:
--   id          : Unique auto-incrementing identifier for this zikr.
--   source      : Optional free-text field for the hadith source.
--   grade       : Reliability grade of the hadith as an ENUM:
--                 ('SAHIH','HASAN','DAIF','UNSPECIFIED'). Defaults to 'UNSPECIFIED'.
--   favorite_id : Nullable FK to favorite(id).
--   created_at  : Timestamp when the row was inserted.
--   updated_at  : Timestamp auto-updated via trigger on any UPDATE.
-- ============================================================================
CREATE TABLE IF NOT EXISTS remembrance
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      VARCHAR,
    grade       ENUM('SAHIH', 'HASAN', 'DAIF', 'UNSPECIFIED') NOT NULL DEFAULT 'UNSPECIFIED',
    favorite_id BIGINT UNIQUE
                    REFERENCES favorite (id) ON DELETE SET NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_remembrance__favorite_id
    ON remembrance (favorite_id);

-- ============================================================================
-- Table: remembrance_translation
-- Each row holds a translation of the core zikr text for one locale.
-- ============================================================================
CREATE TABLE IF NOT EXISTS remembrance_translation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remembrance_id BIGINT                   NOT NULL
        REFERENCES remembrance (id) ON DELETE CASCADE,
    locale_code    VARCHAR                  NOT NULL,
    text           VARCHAR                  NOT NULL CHECK (LENGTH(text) > 0),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (remembrance_id, locale_code)
);

CREATE INDEX IF NOT EXISTS idx_rt__by_remembrance
    ON remembrance_translation (remembrance_id);

CREATE INDEX IF NOT EXISTS idx_rt__by_locale
    ON remembrance_translation (locale_code);

-- ============================================================================
-- Table: explanation_translation
-- Each row holds a translation of the explanation/commentary for a zikr.
-- ============================================================================
CREATE TABLE IF NOT EXISTS explanation_translation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remembrance_id BIGINT                   NOT NULL
        REFERENCES remembrance (id) ON DELETE CASCADE,
    locale_code    VARCHAR                  NOT NULL,
    text           VARCHAR                  NOT NULL CHECK (LENGTH(text) > 0),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (remembrance_id, locale_code)
);

CREATE INDEX IF NOT EXISTS idx_et__by_remembrance
    ON explanation_translation (remembrance_id);

CREATE INDEX IF NOT EXISTS idx_et__by_locale
    ON explanation_translation (locale_code);

-- ============================================================================
-- Table: tag
-- Each row defines one tag that can be applied to remembrances.
--
-- Case-insensitive uniqueness enforced via functional unique index on LOWER(name).
-- ============================================================================
CREATE TABLE IF NOT EXISTS tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR                  NOT NULL,
    name_lower VARCHAR GENERATED ALWAYS AS (LOWER(name)),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Case-insensitive uniqueness via generated column
CREATE UNIQUE INDEX IF NOT EXISTS uq_tag__name_nocase
    ON tag (name_lower);

-- ============================================================================
-- Table: remembrance_tag
-- Join table implementing many-to-many between remembrances and tags.
-- ============================================================================
CREATE TABLE IF NOT EXISTS remembrance_tag
(
    remembrance_id BIGINT NOT NULL
        REFERENCES remembrance (id) ON DELETE CASCADE,
    tag_id         BIGINT NOT NULL
        REFERENCES tag (id) ON DELETE CASCADE,
    PRIMARY KEY (remembrance_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_remembrance_tag__by_remembrance
    ON remembrance_tag (remembrance_id);

CREATE INDEX IF NOT EXISTS idx_remembrance_tag__by_tag
    ON remembrance_tag (tag_id);

-- =========================================================================
-- View: remembrance_with_favorite
-- Purpose:
--   Show all remembrances with a computed `is_favorite` flag (true/false).
-- =========================================================================
CREATE VIEW IF NOT EXISTS remembrance_with_favorite AS
SELECT r.*, CASE WHEN r.favorite_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_favorite
FROM remembrance r;
